ARG BASE_IMAGE="scratch"
FROM ${BASE_IMAGE}

# Installs packedes
RUN apt-get install -y ros-humble-pcl-conversions

# Builds Livox SDK2
RUN git clone https://github.com/Livox-SDK/Livox-SDK2.git \
    && cd Livox-SDK2 \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make -j \
    && sudo make install
