ARG BASE_IMAGE="scratch"
FROM ${BASE_IMAGE}

# Uncomment for x86
# RUN mkdir -p /opt/hpcx/ompi/lib/x86_64-linux-gnu
# RUN ln -s /opt/hpcx/ompi /opt/hpcx/ompi/lib/x86_64-linux-gnu/openmpi

# Installs packedes
RUN apt-get install -y ros-humble-pcl-conversions

# Builds Livox SDK2
RUN git clone https://github.com/Livox-SDK/Livox-SDK2.git \
    && cd Livox-SDK2 \
    && mkdir build \
    && cd build \
    && cmake .. \
    && make -j \
    && sudo make install
